### ISSUE TITLE
Adding support for accounts

### ISSUE THREAD

**Issue by samuelandert** [Raathigesh/SemanticEdit#8]
Create new account.
Login to existing account.

**Comment by samuelandert** [comment]
I was playing a little with an react starting boilerplate and added semantic ui to it. 
What do you think about combining the both, SemanticEdit and SemanticBase? It has already a basic routing structure and basic accounts support. 
https://github.com/CO-OPEN/SemanticBase

**Comment by Raathigesh** [comment]
SemanticEdit already uses [the kickstart-simple by thereactivestack](https://github.com/thereactivestack/kickstart-simple). We could combine but we have to convert to es6 while we are merging since SemanticEdit uses es6 syntax. And the kickstart-simple by thereactivestack already has authentication integrated So we could simply merge from there too.

**Comment by samuelandert** [comment]
That makes it of course much simpler! +1

**Comment by Raathigesh** [comment]
After the discontinuation of the meteor free hosting service, SemanticEdit moved away from meteor and currently its just a client side tool powered by react. And I intend to keep it as a simple tool which makes working with Semantic-UI a little bit easier. 

So at this point I don't have plans to add an account support so closing this issue.
